# :file: .travis.yml
#
# :url:  https://travis-ci.org/bcda-aps/adl2pydm
#
# for advice, see:
#  https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle
#  https://docs.travis-ci.com/user/languages/python


dist: xenial   # required for Python >= 3.7
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  # - "nightly"

before_script:
  # uses standard python
  # must have no special requirements
  - python --version
  - which coveralls

# command to run tests
script:
  - which coverage
  - coverage run tests/

after_success:
  - coverage report -m
  - which coveralls
  - coveralls
  - source deactivate
