name: Unit Tests

on: [push]

jobs:
  build-linux:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - shell: bash -l {0}
      run: pip install pytest

    - name: Run tests with pytest
      run: |
        pytest -vvv .
      env:
        PY_VER: ${{ matrix.python-version }}

    - name: Run the application, show version
      run: |
        adl2pydm --version
      env:
        PY_VER: ${{ matrix.python-version }}
